/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "main.h"

int main(void)
{
	RCC_AHB1ENR_t volatile *const pClkCtrlReg = ADDR_REG_AHB1ENR;
	GPIOx_MODER_t volatile *const pPortDModeReg = ADDR_REG_GPIOD_MODE;
	GPIOx_ODR_t volatile *const pPortDOutReg = ADDR_REG_GPIOD_ODR;

	pClkCtrlReg->GPIODEN = CLOCK_ENABLE;
	pPortDModeReg->MODER12 = MODE_CONF_OUTPUT;

	while(1){
		pPortDOutReg->ODR12 = PIN_STATE_HIGH;
		//introduce small human observable delay
		// this loop executes for 300K times
		for(uint32_t i=0;i<DELAY_COUNT;i++);
		pPortDOutReg->ODR12 = PIN_STATE_LOW;
		for(uint32_t i=0;i<DELAY_COUNT;i++);
	}
}

